# Generated by Django 5.2.7 on 2025-10-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Unknown', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='pin',
            field=models.CharField(default='Unknown', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(default='Unknown', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.CharField(default='Unknown', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
