# Generated by Django 5.2.7 on 2025-11-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_revenue',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Thành công', 'Thành công')], default='Đang xử lý', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
