# Generated by Django 5.2.7 on 2025-11-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_dailyrevenue_order_shipping_status_and_more'),
        ('payment', '0003_order_shipping_status_alter_order_amount_paid_and_more'),
    ]

    operations = [
    ]
